// <auto-generated />
namespace CalculationCSharp.Migrations.CalculationContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddCalcTeamsMembers : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddCalcTeamsMembers));
        
        string IMigrationMetadata.Id
        {
            get { return "201709192003043_AddCalcTeamsMembers"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
