// <auto-generated />
namespace CalculationCSharp.Migrations.CalculationContext
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addcalcowner : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addcalcowner));
        
        string IMigrationMetadata.Id
        {
            get { return "201709221719433_add calc owner "; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
